### PR TITLE
Made updates to starter project based on Gatsby feedback

### PR DESCRIPTION
**Pull request by jonalecpalustre**
Made update based on this trello board - https://trello.com/c/YxxddvW9/493-gatsby-cloud-doc-support

- Updated `package.json` to support Gatsby version 2.22.3 and above
- Updated `package.json` to update ButterCMS plug in to version 2.1.2
- Ran `npm update`
- added a 404.js page
- Applied changes based on this - https://github.com/moonmeister/test-buttercms/commit/115ebe144a69abeb1891e7ca120005e1253085c7

### CODE REVIEW

**Comment by jonalecpalustre** [comment]
Looks like `node_modules` was included on this commit. Should we exclude this? (add to .gitignore)?

**Comment by jakelumetta** [comment]
@jonalecpalustre Yeah, we don't want to include `node_modules`. Please to .gitignore and remove

**Comment by jonalecpalustre** [comment]
@jakelumetta done ✅ Thanks!

**Comment by jakelumetta** [comment]
@jonalecpalustre Looking good! We will need to update the version of our source plugin once it's enhanced to support webhooks but we can do that in a follow up PR. Going to merge this now.

**Pull request merged**
